spring:
  config:
    import: optional:secrets.properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'